name: Build APK

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11

    - name: Check project structure
      run: |
        echo "=== Project Structure ==="
        pwd
        ls -la
        echo "=== Searching for gradlew ==="
        find . -name "gradlew" -type f | head -10 || echo "No gradlew found"

    - name: Setup Gradle
      run: |
        # اگر gradlew وجود دارد از آن استفاده کن، در غیر این صورت از gradle
        if [ -f "./gradlew" ]; then
          chmod +x ./gradlew
          echo "Using existing gradlew"
        else
          echo "Using system gradle"
          # اگر gradlew ندارید، این خط را حذف کنید
          gradle wrapper
          chmod +x ./gradlew
        fi

    - name: Build with Gradle
      run: |
        if [ -f "./gradlew" ]; then
          ./gradlew assembleDebug --no-daemon
        else
          gradle assembleDebug --no-daemon
        fi

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RelayControlApp-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
