name: Build APK

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11

    - name: Install Gradle
      run: |
        # نصب Gradle
        sudo apt-get update
        sudo apt-get install -y gradle

    - name: Verify Gradle installation
      run: gradle --version

    - name: Build Debug APK
      run: gradle assembleDebug --no-daemon

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RelayControlApp-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
